### ISSUE TITLE
Deleting fields is not possible

### ISSUE THREAD

**Issue by m-knorr** [wireshell/wireshell#29] opened 2015-07-16 08:20 UTC
Currently we don't have the option do delete fields.

It's not possible through the PW Interface (the checkbox is inactive) nor through the wireshell commands.

Or am I doing something wrong? :)

**Comment by marcus-herrmann** [comment] 2015-07-16 08:30
In case the checkbox is inactive in the interface the field is still assigned to a template.

For wireshell, we'd have to implement a check for an assignment, this could be an idea for version 1.0 or later.

**Comment by m-knorr** [comment] 2015-07-16 08:32
Yes of course. But the select in the top right of the field window says, its assigned to a "wireshell" template. The problem is, I can't find this template in any template listing... :(

**Comment by marcus-herrmann** [comment] 2015-07-16 08:45
Ahh, I see what you mean. That's a fieldgroup necessary to create fields and should serve as an intermediary container until the field is assigned to a template. Thanks for the hint that this prevents deleting via interface!

**Comment by justonestep** [comment] 2015-07-16 08:52
I got the same issue yesterday. The problem is the assigned "wireshell" fieldgroup. As a quickfix have a look at the fields table and get the id of the affected field. Then delete from table fieldgroups_fields where fields_id equals the field id. Now you be able to delete the field trough PW interface.

**Comment by justonestep** [comment] 2015-07-16 08:56
@marcus-herrmann Why do we need a fieldgroup assignment? If you create a simple field via ProcessWire interface, there is no fieldgroup assigned. I tested commenting out the fieldgroup assignment part in the command and the field was created successfully as well.

**Comment by marcus-herrmann** [comment] 2015-07-16 09:10
Interesting. When I created the command a while ago that didn't work. But makes this easier to fix. ;)

**Comment by m-knorr** [comment] 2015-07-16 11:10
I made it work with deleting the field and fields reference directly in the database. ;)

The problem why I had to delete the field was, that I tried another Fieldtype (CroppableImage) while creating it through wireshell, but due to the fact, that wireshell currently supports only the default fieldtypes the process defaults to "text" :)

**Comment by justonestep** [comment] 2015-10-16 13:36
Fixed in version 0.5.0.

**Closed by justonestep** 2015-10-16 13:36 UTC
Labels: bug
